export const PRODUCKS_MOCK = [
    {
      id: "1a2b3c4d-5e6f-7a8b-9c0d-123456789001",
      name: "Capa Fosca Holográfica",
      description: "Capa protetora fosca com efeito holográfico para iPhone.",
      category: "Capas de celular",
      price: 59.9,
      stock: 25,
      sku: "CAPA-001",
      images: [
        "https://uebecom.com/cdn/shop/products/capa-de-celular-iphone-fosco-holografica-luxo-loveholo-uebecom-4.webp",
      ],
      created_at: new Date(),
    },
    {
      id: "1a2b3c4d-5e6f-7a8b-9c0d-123456789002",
      name: "Camiseta Oversized Branca",
      description: "Camiseta confortável com modelagem oversized.",
      category: "Roupas",
      price: 89.9,
      stock: 50,
      sku: "ROUPA-001",
      images: [
        "https://images.unsplash.com/photo-1541099649105-f69ad21f3246",
      ],
      created_at: new Date(),
    },
    {
      id: "1a2b3c4d-5e6f-7a8b-9c0d-123456789003",
      name: "Mochila Urbana Preta",
      description: "Mochila resistente com espaço para notebook.",
      category: "Mochilas",
      price: 149.9,
      stock: 30,
      sku: "MOCH-001",
      images: [
        "https://images.unsplash.com/photo-1585386959984-a41552262b4d",
      ],
      created_at: new Date(),
    },
    {
      id: "1a2b3c4d-5e6f-7a8b-9c0d-123456789004",
      name: "Capa Transparente Antishock",
      description: "Capa com proteção extra contra quedas e impactos.",
      category: "Capas de celular",
      price: 39.9,
      stock: 15,
      sku: "CAPA-002",
      images: [
        "https://images.unsplash.com/photo-1611605698323-d2d3eab5fd0c",
      ],
      created_at: new Date(),
    },
    {
      id: "1a2b3c4d-5e6f-7a8b-9c0d-123456789005",
      name: "Camiseta Estampada Skate",
      description: "Camiseta com estampa urbana para estilo streetwear.",
      category: "Roupas",
      price: 99.0,
      stock: 60,
      sku: "ROUPA-002",
      images: [
        "https://images.unsplash.com/photo-1533867611509-e4a51f6b5729",
      ],
      created_at: new Date(),
    },
    {
      id: "1a2b3c4d-5e6f-7a8b-9c0d-123456789006",
      name: "Mochila Escolar Azul",
      description: "Ideal para o dia a dia escolar, com compartimento para livros.",
      category: "Mochilas",
      price: 119.9,
      stock: 40,
      sku: "MOCH-002",
      images: [
        "https://images.unsplash.com/photo-1588776814546-fb6a6ec2ce6e",
      ],
      created_at: new Date(),
    },
    {
      id: "1a2b3c4d-5e6f-7a8b-9c0d-123456789007",
      name: "Capa Silicone Minimalista",
      description: "Capa macia e lisa, com textura emborrachada.",
      category: "Capas de celular",
      price: 29.9,
      stock: 80,
      sku: "CAPA-003",
      images: [
        "https://images.unsplash.com/photo-1555617117-08fda4b2035b",
      ],
      created_at: new Date(),
    },
    {
      id: "1a2b3c4d-5e6f-7a8b-9c0d-123456789008",
      name: "Jaqueta Corta Vento",
      description: "Proteção leve contra vento e chuva, ideal para meia estação.",
      category: "Roupas",
      price: 179.9,
      stock: 20,
      sku: "ROUPA-003",
      images: [
        "https://images.unsplash.com/photo-1618354691510-364d1ef3b055",
      ],
      created_at: new Date(),
    },
    {
      id: "1a2b3c4d-5e6f-7a8b-9c0d-123456789009",
      name: "Mochila Vintage Couro",
      description: "Estilo retrô com acabamento em couro sintético.",
      category: "Mochilas",
      price: 199.9,
      stock: 10,
      sku: "MOCH-003",
      images: [
        "https://images.unsplash.com/photo-1577650924092-b4f0a1aa6a3f",
      ],
      created_at: new Date(),
    },
    {
      id: "1a2b3c4d-5e6f-7a8b-9c0d-123456789010",
      name: "Camiseta Básica Preta",
      description: "Essencial no guarda-roupa, confortável e versátil.",
      category: "Roupas",
      price: 49.9,
      stock: 100,
      sku: "ROUPA-004",
      images: [
        "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
      ],
      created_at: new Date(),
    },
  ];
  export const INFLUENCERS_MOCK = [
    {
      id: "f1a2b3c4-d5e6-7890-abcd-000000000001",
      first_name: "Maria",
      last_name: "Silva",
      name: "Maria Silva",
      email: "maria.silva@example.com",
      handle: "@maria",
      redesocial: "@maria",
      category: "Instagramer",
      description: "Lifestyle, moda e viagens.",
      password: "hashedpassword1",
      role: "influencer",
      created_at: new Date(),
    },
    {
      id: "f1a2b3c4-d5e6-7890-abcd-000000000002",
      first_name: "João",
      last_name: "Vlog",
      name: "João Vlog",
      email: "joao.vlog@example.com",
      handle: "@joaovlog",
      redesocial: "@joaovlog",
      category: "Youtuber",
      description: "Vlogs semanais e tecnologia.",
      password: "hashedpassword2",
      role: "influencer",
      created_at: new Date(),
    },
    {
      id: "f1a2b3c4-d5e6-7890-abcd-000000000003",
      first_name: "Beatriz",
      last_name: "Trendy",
      name: "Beatriz Trendy",
      email: "bia.trendy@example.com",
      handle: "@biatrends",
      redesocial: "@biatrends",
      category: "Tiktoker",
      description: "Tendências de TikTok e humor.",
      password: "hashedpassword3",
      role: "influencer",
      created_at: new Date(),
    },
    {
      id: "f1a2b3c4-d5e6-7890-abcd-000000000004",
      first_name: "Lucas",
      last_name: "Tech",
      name: "Lucas Tech",
      email: "lucas.tech@example.com",
      handle: "@lucastech",
      redesocial: "@lucastech",
      category: "Youtuber",
      description: "Tech reviews e gadgets.",
      password: "hashedpassword4",
      role: "influencer",
      created_at: new Date(),
    },
    {
      id: "f1a2b3c4-d5e6-7890-abcd-000000000005",
      first_name: "Nina",
      last_name: "Style",
      name: "Nina Style",
      email: "nina.style@example.com",
      handle: "@ninalife",
      redesocial: "@ninalife",
      category: "Instagramer",
      description: "Beleza e cuidados pessoais.",
      password: "hashedpassword5",
      role: "influencer",
      created_at: new Date(),
    },
    {
      id: "f1a2b3c4-d5e6-7890-abcd-000000000006",
      first_name: "Carlos",
      last_name: "Gamer",
      name: "Carlos Gamer",
      email: "carlos.gamer@example.com",
      handle: "@carlosgamer",
      redesocial: "@carlosgamer",
      category: "Youtuber",
      description: "Gameplay e lives.",
      password: "hashedpassword6",
      role: "influencer",
      created_at: new Date(),
    },
    {
      id: "f1a2b3c4-d5e6-7890-abcd-000000000007",
      first_name: "Ana",
      last_name: "Foodie",
      name: "Ana Foodie",
      email: "ana.foodie@example.com",
      handle: "@anafoodie",
      redesocial: "@anafoodie",
      category: "Instagramer",
      description: "Comida e receitas.",
      password: "hashedpassword7",
      role: "influencer",
      created_at: new Date(),
    },
    {
      id: "f1a2b3c4-d5e6-7890-abcd-000000000008",
      first_name: "Pedro",
      last_name: "Fit",
      name: "Pedro Fit",
      email: "pedro.fit@example.com",
      handle: "@pedrofit",
      redesocial: "@pedrofit",
      category: "Instagramer",
      description: "Fitness e vida saudável.",
      password: "hashedpassword8",
      role: "influencer",
      created_at: new Date(),
    },
    {
      id: "f1a2b3c4-d5e6-7890-abcd-000000000009",
      first_name: "Larissa",
      last_name: "Books",
      name: "Larissa Books",
      email: "larissa.books@example.com",
      handle: "@larissabooks",
      redesocial: "@larissabooks",
      category: "Tiktoker",
      description: "Livros e resenhas.",
      password: "hashedpassword9",
      role: "influencer",
      created_at: new Date(),
    },
    {
      id: "f1a2b3c4-d5e6-7890-abcd-000000000010",
      first_name: "Bruno",
      last_name: "News",
      name: "Bruno News",
      email: "bruno.news@example.com",
      handle: "@brunonews",
      redesocial: "@brunonews",
      category: "Youtuber",
      description: "Notícias e atualidades.",
      password: "hashedpassword10",
      role: "influencer",
      created_at: new Date(),
    },
  ];
  